### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by ATP-BME** [AngusMonroe/ContrastPool#1]
When I tried to train, I encountered the following error:

Traceback (most recent call last):
  File "main.py", line 406, in <module>
    main()
  File "main.py", line 403, in main
    train_val_pipeline(MODEL_NAME, DATASET_NAME, params, net_params, dirs)
  File "main.py", line 112, in train_val_pipeline
    epoch_train_loss, epoch_train_acc, optimizer = train_epoch(model, optimizer, device, train_loader, epoch)
  File "/data0/liushuyu/project/ContrastPool/train_TUs_graph_classification.py", line 29, in train_epoch_sparse
    batch_scores = model.forward(batch_graphs, batch_x, batch_e)
  File "/data0/liushuyu/project/ContrastPool/nets/contrastpool_net.py", line 233, in forward
    self.cal_contrast_adj(device=h.device)
  File "/data0/liushuyu/project/ContrastPool/nets/contrastpool_net.py", line 167, in cal_contrast_adj
    for i in self.adj_dict.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

It appears that the cal_contrast function has not been called, resulting in self.adj_dict()==None. Where should I call cal_contrast?

**Comment by ATP-BME** [comment]
The initial error was 
Traceback (most recent call last):                                                                                                                                                                                                                                 
  File "main.py", line 406, in <module>                                                                                                                                                                                                                            
    main()                                                                                                                                                                                                                                                         
  File "main.py", line 402, in main                                                                                                                                                                                                                                
    net_params['total_param'] = view_model_param(MODEL_NAME, net_params)                                                                                                                                                                                           
  File "main.py", line 34, in view_model_param                                                                                                                                                                                                                     
    model = gnn_model(MODEL_NAME, net_params)                                                                                                                                                                                                                      
  File "/data0/liushuyu/project/ContrastPool/nets/load_net.py", line 17, in gnn_model                                                                                                                                                                              
    model = models[MODEL_NAME](net_params)                                                                                                                                                                                                                         
  File "/data0/liushuyu/project/ContrastPool/nets/load_net.py", line 10, in ContrastPool                                                                                                                                                                           
    return ContrastPoolNet(net_params)                                                                                                                                                                                                                             
  File "/data0/liushuyu/project/ContrastPool/nets/contrastpool_net.py", line 53, in __init__                                                                                                                                                                       
    self.assign_dim = int(net_params['max_num_node'] * pool_ratio)                                                                                                                                                                                                 
KeyError: 'max_num_node' 

Should I add ContrastPool to the code below?
if MODEL_NAME in ['DiffPool', 'DiffCS']:
        net_params['max_num_node'] = dataset.node_num
        # calculate assignment dimension: pool_ratio * largest graph's maximum
        # number of nodes  in the dataset
        num_nodes = [dataset.all[i][0].number_of_nodes() for i in range(len(dataset.all))]
        max_num_node = max(num_nodes)
        net_params['assign_dim'] = int(max_num_node * net_params['pool_ratio']) * net_params['batch_size']

**Comment by AngusMonroe** [comment]
Hi,

Sorry for the late reply. Could you provide the command you used for training so that I can better reproduce the error you met?

**Comment by AngusMonroe** [comment]
This bug has already been fixed in the latest commit. Thanks @ATP-BME
